### PR TITLE
Made minor changes to the README file

### PR DESCRIPTION
**Pull request by gianick**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @gianick,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by gianick** [comment]
Signed the Lightbend CLA

**Review by wsargent — APPROVED** [review]
LGTM

**Comment by wsargent** [comment]
Needs forward port, will add another PR

**Pull request merged**
